// Minecraft-style 9-slot hotbar and Full Inventory catalog for Wildergrid

export const DEFAULT_HOTBAR_SLOTS = [
  {
    id: 'brick_lavender',
    name: 'Lavender Pastel Brick',
    type: 'brick',
    color: '#9d4edd',
    icon: 'Box',
    count: 64,
  },
  {
    id: 'brick_rose',
    name: 'Rose Pastel Brick',
    type: 'brick',
    color: '#ff6b8b',
    icon: 'Box',
    count: 64,
  },
  {
    id: 'brick_buttermint',
    name: 'Butter Mint Brick',
    type: 'brick',
    color: '#a7f3d0',
    icon: 'Box',
    count: 64,
  },
  {
    id: 'brick_skyblue',
    name: 'Sky Blue Brick',
    type: 'brick',
    color: '#00bbf9',
    icon: 'Box',
    count: 64,
  },
  {
    id: 'brick_obsidian',
    name: 'Obsidian Dark Brick',
    type: 'brick',
    color: '#1e293b',
    icon: 'Box',
    count: 64,
  },
  {
    id: 'brick_lemon',
    name: 'Lemon Cream Brick',
    type: 'brick',
    color: '#fde68a',
    icon: 'Box',
    count: 64,
  },
  {
    id: 'prop_lego_chair',
    name: 'Lego Mini Chair',
    type: 'prop',
    propId: 'lego_chair',
    color: '#ffd166',
    icon: 'Armchair',
    count: 16,
  },
  {
    id: 'prop_lego_table',
    name: 'Lego Mini Table',
    type: 'prop',
    propId: 'lego_table',
    color: '#ff9f1c',
    icon: 'Coffee',
    count: 16,
  },
  {
    id: 'prop_lego_lantern',
    name: 'Glowing Amber Lantern',
    type: 'prop',
    propId: 'lego_lantern',
    color: '#ffb703',
    icon: 'Flame',
    count: 16,
  },
];

export const INVENTORY_CATALOG = [
  // Pastel Bricks
  {
    id: 'brick_lavender',
    name: 'Lavender Pastel Brick',
    category: 'bricks',
    type: 'brick',
    color: '#9d4edd',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_rose',
    name: 'Rose Pastel Brick',
    category: 'bricks',
    type: 'brick',
    color: '#ff6b8b',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_buttermint',
    name: 'Butter Mint Brick',
    category: 'bricks',
    type: 'brick',
    color: '#a7f3d0',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_skyblue',
    name: 'Sky Blue Brick',
    category: 'bricks',
    type: 'brick',
    color: '#00bbf9',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_obsidian',
    name: 'Obsidian Dark Brick',
    category: 'bricks',
    type: 'brick',
    color: '#1e293b',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_lemon',
    name: 'Lemon Cream Brick',
    category: 'bricks',
    type: 'brick',
    color: '#fde68a',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_coral',
    name: 'Tropical Coral Brick',
    category: 'bricks',
    type: 'brick',
    color: '#f97316',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_mint',
    name: 'Emerald Mint Brick',
    category: 'bricks',
    type: 'brick',
    color: '#2ec4b6',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_white',
    name: 'Soft Pearl Brick',
    category: 'bricks',
    type: 'brick',
    color: '#f8fafc',
    icon: 'Box',
    defaultCount: 64,
  },
  {
    id: 'brick_bubblegum',
    name: 'Bubblegum Pink Brick',
    category: 'bricks',
    type: 'brick',
    color: '#ec4899',
    icon: 'Box',
    defaultCount: 64,
  },

  // Interior Props
  {
    id: 'prop_lego_chair',
    name: 'Lego Mini Chair',
    category: 'props',
    type: 'prop',
    propId: 'lego_chair',
    color: '#ffd166',
    icon: 'Armchair',
    defaultCount: 16,
  },
  {
    id: 'prop_lego_table',
    name: 'Lego Mini Table',
    category: 'props',
    type: 'prop',
    propId: 'lego_table',
    color: '#ff9f1c',
    icon: 'Coffee',
    defaultCount: 16,
  },
  {
    id: 'prop_lego_lantern',
    name: 'Glowing Amber Lantern',
    category: 'props',
    type: 'prop',
    propId: 'lego_lantern',
    color: '#ffb703',
    icon: 'Flame',
    defaultCount: 16,
  },
  {
    id: 'prop_lego_plant',
    name: 'Mini Succulent Pot',
    category: 'props',
    type: 'prop',
    propId: 'lego_plant',
    color: '#10b981',
    icon: 'Flower2',
    defaultCount: 16,
  },
  {
    id: 'prop_lego_bookshelf',
    name: 'Mini Pastel Bookshelf',
    category: 'props',
    type: 'prop',
    propId: 'lego_bookshelf',
    color: '#8b5cf6',
    icon: 'BookOpen',
    defaultCount: 16,
  },

  // Nature & Glass
  {
    id: 'brick_glass',
    name: 'Frosted Glass Brick',
    category: 'nature',
    type: 'brick',
    color: '#e0f2fe',
    icon: 'Sparkles',
    defaultCount: 32,
  },
  {
    id: 'brick_emerald_leaves',
    name: 'Hedge Foliage Brick',
    category: 'nature',
    type: 'brick',
    color: '#059669',
    icon: 'Trees',
    defaultCount: 48,
  },
];
