export const DOMAINS = {
  EXTERIOR: 'exterior',
  INTERIOR: 'interior',
};

export const VIEW_MODES = {
  ISOMETRIC: 'isometric',
  TOP_DOWN: 'top_down',
};

// ==========================================
// EXTERIOR (CITY & RESORT) INVENTORY ITEMS
// ==========================================
export const EXTERIOR_CATEGORIES = [
  { id: 'all', label: 'All Items', icon: 'Sparkles' },
  { id: 'grounds', label: '🏝️ Grounds', icon: 'Grid3X3' },
  { id: 'architecture', label: '🏛️ Architecture', icon: 'Building' },
  { id: 'foliage', label: '🌴 Palms & Flora', icon: 'Trees' },
  { id: 'amenities', label: '⛱️ City Amenities', icon: 'Sun' },
];

export const EXTERIOR_ITEMS = {
  // Grounds
  'ground_sand': {
    id: 'ground_sand',
    name: 'White Beach Sand',
    category: 'grounds',
    domain: DOMAINS.EXTERIOR,
    type: 'terrain',
    description: 'Fine ivory tropical beach sand that stays cool in the sun.',
    colors: { top: '#fff6ed', sideLeft: '#fae1dd', sideRight: '#ebd2cc' },
    elevation: 0,
    icon: 'Sun',
  },
  'ground_lawn': {
    id: 'ground_lawn',
    name: 'Resort Emerald Lawn',
    category: 'grounds',
    domain: DOMAINS.EXTERIOR,
    type: 'terrain',
    description: 'Manicured tropical turf with emerald luster.',
    colors: { top: '#57cc99', sideLeft: '#38a37f', sideRight: '#227f62' },
    elevation: 0,
    icon: 'Leaf',
  },
  'ground_boardwalk': {
    id: 'ground_boardwalk',
    name: 'Pastel Boardwalk',
    category: 'grounds',
    domain: DOMAINS.EXTERIOR,
    type: 'terrain',
    description: 'Sun-bleached pastel timber planks along the promenade.',
    colors: { top: '#ffe3b0', sideLeft: '#e8c48a', sideRight: '#d1a868' },
    elevation: 0,
    icon: 'Columns',
  },
  'ground_pool': {
    id: 'ground_pool',
    name: 'Sparkling Pool Water',
    category: 'grounds',
    domain: DOMAINS.EXTERIOR,
    type: 'terrain',
    description: 'Crystal turquoise swimming pool reflecting azure blue skies.',
    colors: { top: '#48cae4', sideLeft: '#0096c7', sideRight: '#023e8a' },
    elevation: 0,
    icon: 'Droplets',
  },
  'ground_patio': {
    id: 'ground_patio',
    name: 'Pink Coral Terrace',
    category: 'grounds',
    domain: DOMAINS.EXTERIOR,
    type: 'terrain',
    description: 'Circular pastel coral terrace matching the villa entrance.',
    colors: { top: '#ff8da1', sideLeft: '#e66880', sideRight: '#c44d65' },
    elevation: 0,
    icon: 'CircleDot',
  },

  // Architecture (From Reference Image!)
  'arch_pink_pavilion': {
    id: 'arch_pink_pavilion',
    name: 'Curved Pink Pavilion',
    category: 'architecture',
    domain: DOMAINS.EXTERIOR,
    type: 'building',
    description: 'Signature rounded modern upper pavilion in soft coral pink with floor-to-ceiling glass.',
    colors: { top: '#ff8da1', sideLeft: '#ff6b8b', sideRight: '#e6496f' },
    elevation: 2,
    icon: 'Home',
    hasInterior: true,
  },
  'arch_blue_tower': {
    id: 'arch_blue_tower',
    name: 'Aqua Cylindrical Tower',
    category: 'architecture',
    domain: DOMAINS.EXTERIOR,
    type: 'building',
    description: 'Graceful sky blue curved tower module capturing coastal sea breezes.',
    colors: { top: '#80e5ff', sideLeft: '#00bbf9', sideRight: '#0096c7' },
    elevation: 3,
    icon: 'Building2',
    hasInterior: true,
  },
  'arch_yellow_terrace': {
    id: 'arch_yellow_terrace',
    name: 'Sunshine Curved Terrace',
    category: 'architecture',
    domain: DOMAINS.EXTERIOR,
    type: 'building',
    description: 'Cantilevered circular balcony finished in warm sunny yellow with curved glass railings.',
    colors: { top: '#fff0bd', sideLeft: '#ffd166', sideRight: '#f4b836' },
    elevation: 1,
    icon: 'Layers',
  },
  'arch_glass_atrium': {
    id: 'arch_glass_atrium',
    name: 'Glass Wall Atrium',
    category: 'architecture',
    domain: DOMAINS.EXTERIOR,
    type: 'building',
    description: 'Transparent tinted glass suite with white structural pillars.',
    colors: { top: '#e0f7fa', sideLeft: '#b2ebf2', sideRight: '#80deea' },
    elevation: 1,
    icon: 'Maximize2',
    hasInterior: true,
  },
  'arch_yellow_stairs': {
    id: 'arch_yellow_stairs',
    name: 'Yellow Architectural Stairs',
    category: 'architecture',
    domain: DOMAINS.EXTERIOR,
    type: 'building',
    description: 'Sculptural sunshine yellow staircase connecting the ground deck to the first floor.',
    colors: { top: '#fee440', sideLeft: '#ffd166', sideRight: '#f7b801' },
    elevation: 1,
    icon: 'TrendingUp',
  },

  // Palms & Flora (From Reference Image!)
  'flora_royal_palm': {
    id: 'flora_royal_palm',
    name: 'Royal Tropical Palm',
    category: 'foliage',
    domain: DOMAINS.EXTERIOR,
    type: 'prop',
    description: 'Majestic tall palm tree with slender curved trunk and bursting emerald fronds.',
    colors: { trunk: '#d4a373', fronds: '#2ec4b6' },
    icon: 'Trees',
  },
  'flora_coconut_palm': {
    id: 'flora_coconut_palm',
    name: 'Coconut Cluster Palm',
    category: 'foliage',
    domain: DOMAINS.EXTERIOR,
    type: 'prop',
    description: 'Classic beachside coconut palm swaying gracefully in sea air.',
    colors: { trunk: '#b07d62', fronds: '#57cc99' },
    icon: 'Palmtree',
  },
  'flora_bougainvillea': {
    id: 'flora_bougainvillea',
    name: 'Magenta Bougainvillea',
    category: 'foliage',
    domain: DOMAINS.EXTERIOR,
    type: 'prop',
    description: 'Lush tropical shrub overflowing with vibrant magenta blossoms.',
    colors: { bush: '#7209b7', flowers: '#f72585' },
    icon: 'Flower2',
  },
  'flora_white_boulders': {
    id: 'flora_white_boulders',
    name: 'Sculpted White Boulders',
    category: 'foliage',
    domain: DOMAINS.EXTERIOR,
    type: 'prop',
    description: 'Smooth decorative ivory rocks nestled along the architectural stairs.',
    colors: { rock: '#e9ecef', shadow: '#ced4da' },
    icon: 'Mountain',
  },

  // Amenities
  'amenity_sun_cabana': {
    id: 'amenity_sun_cabana',
    name: 'Striped Sun Cabana',
    category: 'amenities',
    domain: DOMAINS.EXTERIOR,
    type: 'prop',
    description: 'Pastel striped beach umbrella with comfortable cushioned sun loungers.',
    colors: { umbrella: '#ff6b8b', stripe: '#ffffff' },
    icon: 'Umbrella',
  },
  'amenity_fountain': {
    id: 'amenity_fountain',
    name: 'Tiered Resort Fountain',
    category: 'amenities',
    domain: DOMAINS.EXTERIOR,
    type: 'prop',
    description: 'Modern minimalist round fountain with illuminated bubbling waters.',
    colors: { basin: '#ffffff', water: '#00bbf9' },
    icon: 'Droplet',
  },
  'amenity_streetlamp': {
    id: 'amenity_streetlamp',
    name: 'Modern Palm Streetlight',
    category: 'amenities',
    domain: DOMAINS.EXTERIOR,
    type: 'prop',
    description: 'Curved brass & glass streetlamp illuminating evening city promenades.',
    colors: { pole: '#334155', glow: '#ffe066' },
    icon: 'Lamp',
  },
};

// ==========================================
// INTERIOR (ROOM & DECOR) INVENTORY ITEMS
// ==========================================
export const INTERIOR_CATEGORIES = [
  { id: 'all', label: 'All Decor', icon: 'Sparkles' },
  { id: 'surfaces', label: '🪨 Flooring', icon: 'Grid' },
  { id: 'walls', label: '🧱 Walls', icon: 'Box' },
  { id: 'living', label: '🛋️ Living Room', icon: 'Armchair' },
  { id: 'dining', label: '🍳 Kitchen & Dining', icon: 'Coffee' },
  { id: 'bedroom', label: '🛏️ Bedroom', icon: 'Bed' },
  { id: 'decor', label: '🪴 Plants & Art', icon: 'Palette' },
];

export const INTERIOR_ITEMS = {
  // Surfaces
  'int_floor_terrazzo': {
    id: 'int_floor_terrazzo',
    name: 'Pastel Terrazzo Floor',
    category: 'surfaces',
    domain: DOMAINS.INTERIOR,
    type: 'floor',
    description: 'Smooth Italian terrazzo speckled with pastel coral, mint, and gold chips.',
    colors: { top: '#f8edeb', sideLeft: '#e8d8d5', sideRight: '#d8c8c5' },
    icon: 'Grid',
  },
  'int_floor_parquet': {
    id: 'int_floor_parquet',
    name: 'Blonde Oak Herringbone',
    category: 'surfaces',
    domain: DOMAINS.INTERIOR,
    type: 'floor',
    description: 'Warm scandi-chic natural wood flooring with chevron pattern.',
    colors: { top: '#faedcd', sideLeft: '#e9d8a6', sideRight: '#d4a373' },
    icon: 'Columns',
  },
  'int_floor_mint': {
    id: 'int_floor_mint',
    name: 'Glazed Mint Tiles',
    category: 'surfaces',
    domain: DOMAINS.INTERIOR,
    type: 'floor',
    description: 'Handmade ceramic square tiles with cool mint glaze.',
    colors: { top: '#d8f3dc', sideLeft: '#b7e4c7', sideRight: '#95d5b2' },
    icon: 'Grid3X3',
  },
  'int_floor_marble': {
    id: 'int_floor_marble',
    name: 'White Calacatta Marble',
    category: 'surfaces',
    domain: DOMAINS.INTERIOR,
    type: 'floor',
    description: 'Pristine white marble tiles with subtle gold and grey veining.',
    colors: { top: '#ffffff', sideLeft: '#f1f5f9', sideRight: '#e2e8f0' },
    icon: 'Square',
  },

  // Walls
  'int_wall_glass': {
    id: 'int_wall_glass',
    name: 'Curved Glass Window Wall',
    category: 'walls',
    domain: DOMAINS.INTERIOR,
    type: 'wall',
    description: 'Floor-to-ceiling panoramic glass facade framing the ocean and palms.',
    colors: { frame: '#ffffff', glass: 'rgba(72, 202, 228, 0.35)' },
    icon: 'Maximize',
  },
  'int_wall_pink': {
    id: 'int_wall_pink',
    name: 'Coral Pink Accent Wall',
    category: 'walls',
    domain: DOMAINS.INTERIOR,
    type: 'wall',
    description: 'Curved structural drywall in calming peach coral.',
    colors: { top: '#ffccd5', sideLeft: '#ffb3c1', sideRight: '#ff758f' },
    icon: 'Square',
  },
  'int_wall_aqua': {
    id: 'int_wall_aqua',
    name: 'Aqua Screen Partition',
    category: 'walls',
    domain: DOMAINS.INTERIOR,
    type: 'wall',
    description: 'Retro-modern fluted glass and turquoise divider screen.',
    colors: { top: '#caf0f8', sideLeft: '#90e0ef', sideRight: '#00b4d8' },
    icon: 'Columns',
  },

  // Living Room
  'int_sofa_curved': {
    id: 'int_sofa_curved',
    name: 'Retro Curved Bouclé Sofa',
    category: 'living',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Organic curved sofa upholstered in soft cream bouclé fabric with coral cushions.',
    colors: { main: '#ff8da1', cushion: '#fff0bd' },
    icon: 'Armchair',
  },
  'int_chair_bubble': {
    id: 'int_chair_bubble',
    name: 'Yellow Egg Bubble Chair',
    category: 'living',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Sculptural retro accent chair in sunny warm yellow.',
    colors: { main: '#ffd166', cushion: '#ffffff' },
    icon: 'Circle',
  },
  'int_table_coffee': {
    id: 'int_table_coffee',
    name: 'Amorphous Terrazzo Table',
    category: 'living',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Pebble-shaped low cocktail table with brass cylinder legs.',
    colors: { top: '#ffffff', legs: '#d4af37' },
    icon: 'Table',
  },
  'int_lamp_sunset': {
    id: 'int_lamp_sunset',
    name: 'Sunset Aura Floor Lamp',
    category: 'living',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Minimalist curved arch lamp projecting warm sunset hues.',
    colors: { base: '#334155', glow: '#ff7b00' },
    icon: 'LampCeiling',
  },
  'int_tv_console': {
    id: 'int_tv_console',
    name: 'Pastel Media Console',
    category: 'living',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Low credenza with tambour fluted doors and ultra-thin smart screen.',
    colors: { body: '#00bbf9', screen: '#1e293b' },
    icon: 'Tv',
  },

  // Dining & Kitchen
  'int_kitchen_island': {
    id: 'int_kitchen_island',
    name: 'Terrazzo Island Bar',
    category: 'dining',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Central kitchen island with waterfall marble counter and induction cooktop.',
    colors: { counter: '#ffffff', base: '#ffccd5' },
    icon: 'Utensils',
  },
  'int_bar_stool': {
    id: 'int_bar_stool',
    name: 'Pastel Yellow Bar Stool',
    category: 'dining',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Tubular curved steel barstool with round cushioned seat.',
    colors: { seat: '#fee440', frame: '#ffffff' },
    icon: 'CircleDot',
  },
  'int_fridge_retro': {
    id: 'int_fridge_retro',
    name: 'Mint Retro Refrigerator',
    category: 'dining',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: '50s inspired curved refrigerator in vintage mint with chrome handles.',
    colors: { body: '#57cc99', chrome: '#ffffff' },
    icon: 'Archive',
  },

  // Bedroom
  'int_bed_platform': {
    id: 'int_bed_platform',
    name: 'Curved Platform Bed',
    category: 'bedroom',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Low floating platform bed with upholstered fluted coral headboard and white linen.',
    colors: { frame: '#ff6b8b', sheets: '#ffffff' },
    icon: 'Bed',
  },
  'int_mirror_arch': {
    id: 'int_mirror_arch',
    name: 'Arched Brass Standing Mirror',
    category: 'bedroom',
    domain: DOMAINS.INTERIOR,
    type: 'furniture',
    description: 'Full-length arched vanity mirror capturing morning sunlight.',
    colors: { frame: '#ffd166', glass: '#e0f7fa' },
    icon: 'Shield',
  },

  // Decor
  'int_plant_monstera': {
    id: 'int_plant_monstera',
    name: 'Potted Giant Monstera',
    category: 'decor',
    domain: DOMAINS.INTERIOR,
    type: 'prop',
    description: 'Flourishing split-leaf tropical monstera in a fluted terracotta planter.',
    colors: { leaves: '#2ec4b6', pot: '#f28482' },
    icon: 'Leaf',
  },
  'int_plant_fig': {
    id: 'int_plant_fig',
    name: 'Fiddle Leaf Fig Tree',
    category: 'decor',
    domain: DOMAINS.INTERIOR,
    type: 'prop',
    description: 'Graceful indoor fig tree with broad glossy emerald foliage.',
    colors: { leaves: '#1b998b', pot: '#ffffff' },
    icon: 'Trees',
  },
  'int_neon_sign': {
    id: 'int_neon_sign',
    name: 'Paradise Neon Sign',
    category: 'decor',
    domain: DOMAINS.INTERIOR,
    type: 'prop',
    description: 'Hand-blown cursive neon wall light glowing in pink and aqua.',
    colors: { glow: '#ff007f' },
    icon: 'Zap',
  },
  'int_record_player': {
    id: 'int_record_player',
    name: 'Vinyl Record Player & Stand',
    category: 'decor',
    domain: DOMAINS.INTERIOR,
    type: 'prop',
    description: 'Mid-century turntable playing breezy tropical bossa nova grooves.',
    colors: { wood: '#d4a373', vinyl: '#0f172a' },
    icon: 'Disc',
  },
};

export const ALL_ITEMS = {
  ...EXTERIOR_ITEMS,
  ...INTERIOR_ITEMS,
};
